### ISSUE TITLE
Actions not reversible

### ISSUE THREAD

**Issue by alerque** [Konfekt/vim-smartbraces#1]
I got excited when I saw this because the behavior of `{` and `}` has always bothered me. I rarely if ever want to be on the blank line before a paragraph and am constantly accounting for that in my usage and even other macros.

However this doesn't work for me as is because it is not reversible. I expect hitting `{}` or `}{` or `}}}{{{` in sequence to end up where I started or at least on the first character of the paragraph where I started.

This plugin makes the jumps inconsistent. Moving forward goes to the start of the _next_ paragraph, so `}}}}` moves forward for paragraphs, but moving backward cycles through the end and start of paragraphs, so `{{{{` only moves backwards two paragraphs.

Additionally from the middle of a paragraph `{` moves to the end of the previous paragraph instead of to the beginning of the current one as expected.

**Comment by Konfekt** [comment]
Indeed `}` did not work as it was meant to if the paragraph consists of a single line. The latest commit 8a001915a0429e2ccf06bb2df5ae6f9474ca6747 should resolve it.

**Comment by alerque** [comment]
Oh that's much nicer, thank you!

**Comment by Konfekt** [comment]
Thank you for having pointed out this oversight! This said, it is tricky to make `{` and `}` respect folds, I  desist for the moment.
