### ISSUE TITLE
Brace no longer combines properly as motion command

### ISSUE THREAD

**Issue by alerque** [Konfekt/vim-smartbraces#2]
Day 2 :wink: with this plugin…

I just hit a keystroke I have well trained in muscle memory, <kbd>d</kbd><kbd>}</kbd>, expecting it to delete through the end of the current paragraph. Instead it did something funky like pasting an extra copy of the first line of the current paragraph into the buffer.

**Comment by Konfekt** [comment]
Thanks for pointing that one out, there is some dust that you whirl up. I hope the last commit fixes that one as well.
