### ISSUE TITLE
Overly greedy match

### ISSUE THREAD

**Issue by alerque** [Konfekt/vim-smartbraces#3]
Given a data file like this:

```
chore(tooling): Install and configure NPM modules for release management


fix(tooling): Conf com

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```
With the cursor on line 2, I expect <kbd>d</kbd><kbd>}</kbd> to have the net effect of removing lines 2, 3, and 4 from the file. Instead it also deletes line 5 and the first character of line 6:

```
chore(tooling): Install and configure NPM modules for release management
 Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
```

**Comment by Konfekt** [comment]
Thanks for pointing out how `{` and `}` did not jump to where they should on empty lines!
The `{` and `}` now jump to where they should when on empty lines. In particular, in operator mode they delete up to where `{` or `}` would jump to. 

However, it would indeed be more useful if `{` and `}` behave differently in operator mode when on empty lines, I think call them twice makes sence to me, to jump to the end instead of start of the paragraph.

But I do not know how to check if `{` or `}` was called in  operator mode.

**Comment by alerque** [comment]
I don't understand how behaving differently depending on where you start from or what mode it is in would be a good thing. In my head at least commands like this are only useful if they are consistent and repeatable: that's what makes editing in `vim` so productive in the first place.

**Comment by Konfekt** [comment]
Okay, so it makes sense that it jumps to the beginning of the next paragraph in-between two of them?!

**Comment by alerque** [comment]
I don't understand your question.

Maybe I can explain it this way. When I hit <kbd>}</kbd> I expect it to jump to the "next paragraph end". (_NOT_ "the end of the next paragraph" which might be different and would regress #1, specifically the "next paragraph end".) Note that with blank lines and whitespace there can be a never-never land between paragraphs that is not part of any paragraph. What I expect is for it to jump forward until my cursor is at the end of a paragraph. If I'm in the middle of a paragraph, that will be the end of the current paragraph. If I'm somewhere before a paragraph, that will be the end of the next paragraph.

And of course the same for <kbd>{</kbd> in reverse.

**Comment by Konfekt** [comment]
Now `{` and `}` jump to the start / end of the current or next paragraph and accept counts.

**Comment by alerque** [comment]
A quick test drive shows this is much improved! Thank you.
